FUNCTION ZCO_SAP_TO_ACS_0002.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  IMPORTING
*"     REFERENCE(PI_IN_WERKS) TYPE  ZCOT0005 OPTIONAL
*"  EXPORTING
*"     REFERENCE(PI_OUT) TYPE  ZCOS_MES_005
*"  TABLES
*"      PI_OUT_TABLE STRUCTURE  ZCOS0004 OPTIONAL
*"----------------------------------------------------------------------
DATA: LV_IMPORT01 TYPE STRING,
      LV_TABLE01  TYPE STRING,
      LV_EXPORT01 TYPE STRING,
      LV_TYPE     TYPE CHAR1,
      LV_MSG      TYPE CHAR220.

IF PI_IN_WERKS[] IS NOT INITIAL.

  SELECT A~AUFNR,
         A~WERKS,
         B~MATNR,
*         B~ZLOTID,
         A~USER6,
         A~AUFEX,
         B~PSMNG,
         B~MEINS
    FROM AUFK AS A
    INNER JOIN AFPO AS B
      ON A~AUFNR = B~AUFNR
    FOR ALL ENTRIES IN @PI_IN_WERKS
   WHERE A~WERKS = @PI_IN_WERKS-WERKS
    INTO TABLE @DATA(LT_TABLE).

  IF LT_TABLE IS INITIAL.
    PI_OUT-EV_TYPE = 'E'.
    PI_OUT-EV_MSG  = '没有取到符合工厂范围的值！'.
  ELSE.
    MOVE-CORRESPONDING LT_TABLE TO PI_OUT_TABLE[].
    PI_OUT-EV_TYPE = 'S'.
    PI_OUT-EV_MSG  = '数据获取成功！'.
  ENDIF.
ELSE.
  PI_OUT-EV_TYPE = 'E'.
  PI_OUT-EV_MSG  = '工厂不允许为空！'.
ENDIF.


*日志数据存储
*传入参数转换JSON
CALL FUNCTION 'Z_RFC_PARAMS_TO_JSON'
  EXPORTING
    IV_PARAM_STRUCTURE = PI_IN_WERKS
  IMPORTING
    EV_JSON_STRING     = LV_IMPORT01.

*传出参数转换JSON
CALL FUNCTION 'Z_RFC_PARAMS_TO_JSON'
  EXPORTING
    IV_PARAM_TABLE = PI_OUT_TABLE[]
  IMPORTING
    EV_JSON_STRING = LV_TABLE01.

*MSG
CALL FUNCTION 'Z_RFC_PARAMS_TO_JSON'
  EXPORTING
    IV_PARAM_STRUCTURE = PI_OUT
  IMPORTING
    EV_JSON_STRING     = LV_EXPORT01.

CALL FUNCTION 'Z_RFC_LOG_WRITE'
  EXPORTING
    IV_FUNCNAME  = 'ZCO_SAP_TO_ACS_0002'
    IV_UNAME     = SY-UNAME
    IV_IMPORT01  = LV_IMPORT01
    IV_EXPORT01  = LV_EXPORT01
    IV_TABLE01   = LV_TABLE01
    IV_TYPE      = LV_TYPE
    IV_MSG       = LV_MSG.




ENDFUNCTION.
