FUNCTION Z_RFC_LOG_WRITE.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  IMPORTING
*"     REFERENCE(IV_FUNCNAME) TYPE  FUNCNAME OPTIONAL
*"     REFERENCE(IV_UNAME) TYPE  UNAME OPTIONAL
*"     REFERENCE(IV_IMPORT01) TYPE  ZRFC_LOG-IMPORT01 OPTIONAL
*"     REFERENCE(IV_IMPORT02) TYPE  ZRFC_LOG-IMPORT02 OPTIONAL
*"     REFERENCE(IV_IMPORT03) TYPE  ZRFC_LOG-IMPORT03 OPTIONAL
*"     REFERENCE(IV_EXPORT01) TYPE  ZRFC_LOG-EXPORT01 OPTIONAL
*"     REFERENCE(IV_EXPORT02) TYPE  ZRFC_LOG-EXPORT02 OPTIONAL
*"     REFERENCE(IV_EXPORT03) TYPE  ZRFC_LOG-EXPORT03 OPTIONAL
*"     REFERENCE(IV_TABLE01) TYPE  ZRFC_LOG-TABLE01 OPTIONAL
*"     REFERENCE(IV_TABLE02) TYPE  ZRFC_LOG-TABLE02 OPTIONAL
*"     REFERENCE(IV_TABLE03) TYPE  ZRFC_LOG-TABLE03 OPTIONAL
*"     REFERENCE(IV_TYPE) TYPE  ZRFC_LOG-TYPE OPTIONAL
*"     REFERENCE(IV_MSG) TYPE  ZRFC_LOG-MSG OPTIONAL
*"----------------------------------------------------------------------



DATA: LV_UUID      TYPE SYSUUID_C32,
      LS_DATA      TYPE ZRFC_LOG,
      LV_TIMESTAMP TYPE TIMESTAMP.

GET TIME STAMP FIELD LV_TIMESTAMP.
LV_TIMESTAMP = LV_TIMESTAMP + 80000. "UTC+8

* 获取UUID唯一标识
TRY.
    CALL METHOD CL_SYSTEM_UUID=>IF_SYSTEM_UUID_STATIC~CREATE_UUID_C32
      RECEIVING
        UUID = LV_UUID.
  CATCH CX_UUID_ERROR .
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDTRY.


CLEAR: LS_DATA.
LS_DATA-UUID       = LV_UUID.
LS_DATA-FUNCNAME   = IV_FUNCNAME.
LS_DATA-UNAME      = IV_UNAME.
LS_DATA-TIMESTAMP  = LV_TIMESTAMP.
LS_DATA-IMPORT01   = IV_IMPORT01.
LS_DATA-IMPORT02   = IV_IMPORT02.
LS_DATA-IMPORT03   = IV_IMPORT03.
LS_DATA-EXPORT01   = IV_EXPORT01.
LS_DATA-EXPORT02   = IV_EXPORT02.
LS_DATA-EXPORT03   = IV_EXPORT03.
LS_DATA-TABLE01    = IV_TABLE01.
LS_DATA-TABLE02    = IV_TABLE02.
LS_DATA-TABLE03    = IV_TABLE03.
LS_DATA-TYPE       = IV_TYPE.
LS_DATA-MSG        = IV_MSG.
LS_DATA-DATUM      = SY-DATUM.

IF LS_DATA IS NOT INITIAL.
  INSERT ZRFC_LOG FROM LS_DATA.
  IF SY-SUBRC <> 0.
    MESSAGE '存储数据失败' TYPE 'E'.
  ENDIF.
ENDIF.

ENDFUNCTION.
