FUNCTION Z_RFC_PARAMS_TO_JSON.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  IMPORTING
*"     REFERENCE(IV_PARAM_STRUCTURE) TYPE  ANY OPTIONAL
*"     REFERENCE(IV_PARAM_TABLE) TYPE  TABLE OPTIONAL
*"  EXPORTING
*"     REFERENCE(EV_JSON_STRING) TYPE  STRING
*"----------------------------------------------------------------------

DATA: LO_WRITER  TYPE REF TO CL_SXML_STRING_WRITER,
      LV_XSTRING TYPE XSTRING.

" 检查是否有表数据
IF IV_PARAM_TABLE IS NOT INITIAL.
  TRY.
      LO_WRITER = CL_SXML_STRING_WRITER=>CREATE( TYPE = IF_SXML=>CO_XT_JSON ).
      CALL TRANSFORMATION ID SOURCE DATA = IV_PARAM_TABLE RESULT XML LO_WRITER.
      LV_XSTRING = LO_WRITER->GET_OUTPUT( ).
      EV_JSON_STRING = CL_ABAP_CODEPAGE=>CONVERT_FROM( LV_XSTRING ).
    CATCH CX_ROOT.
      EV_JSON_STRING = '{"ERROR": "表参数转换失败"}'.
  ENDTRY.

" 检查是否有结构数据
ELSEIF IV_PARAM_STRUCTURE IS NOT INITIAL.
  TRY.
      LO_WRITER = CL_SXML_STRING_WRITER=>CREATE( TYPE = IF_SXML=>CO_XT_JSON ).
      CALL TRANSFORMATION ID SOURCE DATA = IV_PARAM_STRUCTURE RESULT XML LO_WRITER.
      LV_XSTRING = LO_WRITER->GET_OUTPUT( ).
      EV_JSON_STRING = CL_ABAP_CODEPAGE=>CONVERT_FROM( LV_XSTRING ).
    CATCH CX_ROOT.
      EV_JSON_STRING = '{"ERROR": "结构参数转换失败"}'.
  ENDTRY.
ELSE.
  EV_JSON_STRING = '{"MESSAGE": "无参数数据"}'.
ENDIF.

ENDFUNCTION.
